version: '2'
services:
    myappdemo06-app:
        image: myappdemo06
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://myappdemo06-mysql:3306/myappdemo06?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://myappdemo06-elasticsearch:9200
        ports:
            - 8080:8080
    myappdemo06-mysql:
        extends:
            file: mysql.yml
            service: myappdemo06-mysql
    myappdemo06-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: myappdemo06-elasticsearch
